### ISSUE TITLE
Question reagrding OS compatibility

### ISSUE THREAD

**Issue by Tamim-codes** [suchetanrs/ORB-SLAM3-ROS2-Docker#4]
I have come across this repo, and wanted to try it out by myself. Would I be able to run it on my Ubuntu 20.04 where I work with ROS1? I have this doubt as I am expecting the docker wrapper to be a containerized system which will run anywhere irrespective of the OS as per its definition.

**Comment by suchetanrs** [comment]
Hi, thanks for your ticket.
This will work irrespective of your Ubuntu version provided you run it with the docker container. Please let me know if you face any issues.
