### ISSUE TITLE
Is there a simulation environment in the demo in the docker image？

### ISSUE THREAD

**Issue by tulingcheng86** [suchetanrs/ORB-SLAM3-ROS2-Docker#5]
I didn't find it
![image](https://github.com/suchetanrs/ORB-SLAM3-ROS2-Docker/assets/137706055/7779b53b-cf39-4ec8-a993-3ee099bd7cf1)

THANKS

**Comment by suchetanrs** [comment]
Hi, I have updated the simulation setup [here](https://github.com/suchetanrs/scout-husky-gazebo-ros2)
I have also updated the README with a section on how to run this with the simulation. Let me know if this works.
