### ISSUE TITLE
Pull request denied

### ISSUE THREAD

**Issue by tamiimcodes** [suchetanrs/ORB-SLAM3-ROS2-Docker#7]
![Screenshot from 2024-06-11 23-27-43](https://github.com/suchetanrs/ORB-SLAM3-ROS2-Docker/assets/66246902/2d2c9196-3b2d-4116-9353-29ef0df5d77e)

I am unable to run the docker as I come across a request to proceed with a docker login. Is this normal procedure? If so, how should I go about moving forward? Thanks.

**Comment by suchetanrs** [comment]
Hi, did you follow the README? This shouldn't happen if the image is built successfully. The built image should be tagged ```orb-slam3-humble:22.04``` which isn't visible in your docker images list.
